//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorWebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vpsrv.visualset.com.br/PostagemVipp.asmx")]
        public string IntegradorWebService_WSVIPP_PostagemVipp {
            get {
                return ((string)(this["IntegradorWebService_WSVIPP_PostagemVipp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vipp.visualset.com.br")]
        public string Site {
            get {
                return ((string)(this["Site"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PEFycmF5T2ZGb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvP" +
            "k9ic2VydmFjYW8xPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4xPC9Db2x1bmE+PFRhbWFuaG8+MDwvVGFtY" +
            "W5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+P" +
            "E5vbWVBdHJpYnV0bz5RdWFudGlkYWRlPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4xMTwvQ29sdW5hPjxUY" +
            "W1hbmhvPjA8L1RhbWFuaG8+PERlbGltaXRhZG9yLz48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0Y" +
            "WNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Q29udGV1ZG88L05vbWVBdHJpYnV0bz48Q29sdW5hPjEwP" +
            "C9Db2x1bmE+PFRhbWFuaG8+MDwvVGFtYW5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pb" +
            "GhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5PYnNlcnZhY2FvMjwvTm9tZUF0cmlid" +
            "XRvPjxDb2x1bmE+MTM8L0NvbHVuYT48VGFtYW5obz4wPC9UYW1hbmhvPjxEZWxpbWl0YWRvci8+PC9Gb" +
            "3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPkRlc3RpbmF0Y" +
            "XJpbzwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MTU8L0NvbHVuYT48VGFtYW5obz4wPC9UYW1hbmhvPjxEZ" +
            "WxpbWl0YWRvci8+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0c" +
            "mlidXRvPkRvY3VtZW50b0Rlc3RpbmF0YXJpbzwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MTY8L0NvbHVuY" +
            "T48VGFtYW5obz4wPC9UYW1hbmhvPjxEZWxpbWl0YWRvci8+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvc" +
            "m1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPkVuZGVyZWNvPC9Ob21lQXRyaWJ1dG8+PENvbHVuY" +
            "T4xNzwvQ29sdW5hPjxUYW1hbmhvPjA8L1RhbWFuaG8+PERlbGltaXRhZG9yLz48L0Zvcm1hdGFjYW9Qb" +
            "GFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+TnVtZXJvPC9Ob21lQXRyaWJ1d" +
            "G8+PENvbHVuYT4xODwvQ29sdW5hPjxUYW1hbmhvPjA8L1RhbWFuaG8+PERlbGltaXRhZG9yLz48L0Zvc" +
            "m1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+QmFpcnJvPC9Ob" +
            "21lQXRyaWJ1dG8+PENvbHVuYT4xOTwvQ29sdW5hPjxUYW1hbmhvPjA8L1RhbWFuaG8+PERlbGltaXRhZ" +
            "G9yLz48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Q" +
            "29tcGxlbWVudG88L05vbWVBdHJpYnV0bz48Q29sdW5hPjIwPC9Db2x1bmE+PFRhbWFuaG8+MDwvVGFtY" +
            "W5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+P" +
            "E5vbWVBdHJpYnV0bz5DRVA8L05vbWVBdHJpYnV0bz48Q29sdW5hPjIxPC9Db2x1bmE+PFRhbWFuaG8+M" +
            "DwvVGFtYW5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhb" +
            "mlsaGE+PE5vbWVBdHJpYnV0bz5DaWRhZGU8L05vbWVBdHJpYnV0bz48Q29sdW5hPjIyPC9Db2x1bmE+P" +
            "FRhbWFuaG8+MDwvVGFtYW5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtY" +
            "XRhY2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5VRjwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MjM8L0Nvb" +
            "HVuYT48VGFtYW5obz4wPC9UYW1hbmhvPjxEZWxpbWl0YWRvci8+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+P" +
            "EZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPlNlcnZpY288L05vbWVBdHJpYnV0bz48Q29sd" +
            "W5hPjI1PC9Db2x1bmE+PFRhbWFuaG8+MDwvVGFtYW5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb" +
            "1BsYW5pbGhhPjwvQXJyYXlPZkZvcm1hdGFjYW9QbGFuaWxoYT4=")]
        public string LayoutCengage {
            get {
                return ((string)(this["LayoutCengage"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PEFycmF5T2ZGb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvP" +
            "kNvZGlnb0JhcnJhVm9sdW1lPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4yPC9Db2x1bmE+PEluaWNpbz4xP" +
            "C9JbmljaW8+PFRhbWFuaG8+NDwvVGFtYW5obz48RGVsaW1pdGFkb3I+OzwvRGVsaW1pdGFkb3I+PC9Gb" +
            "3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPkNvZGlnb0Jhc" +
            "nJhQ2xpZW50ZTwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MzwvQ29sdW5hPjxJbmljaW8+MTI8L0luaWNpb" +
            "z48VGFtYW5obz4yPC9UYW1hbmhvPjxEZWxpbWl0YWRvcj47PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjY" +
            "W9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+T2JzZXJ2YWNhb1Zpc3Vhb" +
            "DwvTm9tZUF0cmlidXRvPjxDb2x1bmE+NDwvQ29sdW5hPjxJbmljaW8+MTU8L0luaWNpbz48VGFtYW5ob" +
            "z41PC9UYW1hbmhvPjxEZWxpbWl0YWRvcj47PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjYW9QbGFuaWxoY" +
            "T48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Tm9tZTwvTm9tZUF0cmlidXRvPjxDb2x1b" +
            "mE+NTwvQ29sdW5hPjxJbmljaW8+MjE8L0luaWNpbz48VGFtYW5obz40MDwvVGFtYW5obz48RGVsaW1pd" +
            "GFkb3I+OzwvRGVsaW1pdGFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoY" +
            "T48Tm9tZUF0cmlidXRvPkVuZGVyZWNvPC9Ob21lQXRyaWJ1dG8+PEluaWNpbz42MjwvSW5pY2lvPjxDb" +
            "2x1bmE+NjwvQ29sdW5hPjxUYW1hbmhvPjQwPC9UYW1hbmhvPjxEZWxpbWl0YWRvcj47PC9EZWxpbWl0Y" +
            "WRvcj48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Q" +
            "mFpcnJvPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT43PC9Db2x1bmE+PEluaWNpbz4xMDM8L0luaWNpbz48V" +
            "GFtYW5obz4xNTwvVGFtYW5obz48RGVsaW1pdGFkb3I+OzwvRGVsaW1pdGFkb3I+PC9Gb3JtYXRhY2FvU" +
            "GxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPkNpZGFkZTwvTm9tZUF0cmlid" +
            "XRvPjxDb2x1bmE+ODwvQ29sdW5hPjxJbmljaW8+MTE5PC9JbmljaW8+PFRhbWFuaG8+MTU8L1RhbWFua" +
            "G8+PERlbGltaXRhZG9yPjs8L0RlbGltaXRhZG9yPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY" +
            "2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5VRjwvTm9tZUF0cmlidXRvPjxDb2x1bmE+OTwvQ29sdW5hP" +
            "jxJbmljaW8+MTM1PC9JbmljaW8+PFRhbWFuaG8+MjwvVGFtYW5obz48RGVsaW1pdGFkb3I+OzwvRGVsa" +
            "W1pdGFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlid" +
            "XRvPkNFUDwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MTA8L0NvbHVuYT48SW5pY2lvPjEzODwvSW5pY2lvP" +
            "jxUYW1hbmhvPjEwPC9UYW1hbmhvPjxEZWxpbWl0YWRvcj47PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjY" +
            "W9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+RXRpcXVldGE8L05vbWVBd" +
            "HJpYnV0bz48Q29sdW5hPjExPC9Db2x1bmE+PEluaWNpbz4xNDk8L0luaWNpbz48VGFtYW5obz4xMzwvV" +
            "GFtYW5obz48RGVsaW1pdGFkb3I+OzwvRGVsaW1pdGFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PC9Bc" +
            "nJheU9mRm9ybWF0YWNhb1BsYW5pbGhhPg==")]
        public string LayoutUnimed {
            get {
                return ((string)(this["LayoutUnimed"]));
            }
            set {
                this["LayoutUnimed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveFile {
            get {
                return ((string)(this["SaveFile"]));
            }
            set {
                this["SaveFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PEFycmF5T2ZGb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvP" +
            "kNOUEpDUEY8L05vbWVBdHJpYnV0bz48Q29sdW5hPjE8L0NvbHVuYT48SW5pY2lvPjI8L0luaWNpbz48V" +
            "GFtYW5obz4xNDwvVGFtYW5obz48RGVsaW1pdGFkb3I+PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjYW9Qb" +
            "GFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Tk9NRTwvTm9tZUF0cmlidXRvP" +
            "jxDb2x1bmE+MjwvQ29sdW5hPjxJbmljaW8+MTY8L0luaWNpbz48VGFtYW5obz41MDwvVGFtYW5obz48R" +
            "GVsaW1pdGFkb3I+PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsY" +
            "W5pbGhhPjxOb21lQXRyaWJ1dG8+RU1BSUw8L05vbWVBdHJpYnV0bz48Q29sdW5hPjM8L0NvbHVuYT48S" +
            "W5pY2lvPjY2PC9JbmljaW8+PFRhbWFuaG8+NTA8L1RhbWFuaG8+PERlbGltaXRhZG9yPjwvRGVsaW1pd" +
            "GFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvP" +
            "lNFR1VOREFMSU5IQURFU1RJTkFUQVJJTzwvTm9tZUF0cmlidXRvPjxDb2x1bmE+NDwvQ29sdW5hPjxJb" +
            "mljaW8+MTE2PC9JbmljaW8+PFRhbWFuaG8+NTA8L1RhbWFuaG8+PERlbGltaXRhZG9yPjwvRGVsaW1pd" +
            "GFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvP" +
            "kNFUDwvTm9tZUF0cmlidXRvPjxDb2x1bmE+NTwvQ29sdW5hPjxJbmljaW8+MjE2PC9JbmljaW8+PFRhb" +
            "WFuaG8+ODwvVGFtYW5obz48RGVsaW1pdGFkb3I+PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjYW9QbGFua" +
            "WxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+RU5ERVJFQ088L05vbWVBdHJpYnV0b" +
            "z48Q29sdW5hPjY8L0NvbHVuYT48SW5pY2lvPjIyNDwvSW5pY2lvPjxUYW1hbmhvPjUwPC9UYW1hbmhvP" +
            "jxEZWxpbWl0YWRvcj48L0RlbGltaXRhZG9yPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvU" +
            "GxhbmlsaGE+PE5vbWVBdHJpYnV0bz5OVU1FUk88L05vbWVBdHJpYnV0bz48Q29sdW5hPjc8L0NvbHVuY" +
            "T48SW5pY2lvPjI3NDwvSW5pY2lvPjxUYW1hbmhvPjY8L1RhbWFuaG8+PERlbGltaXRhZG9yPjwvRGVsa" +
            "W1pdGFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlid" +
            "XRvPkNPTVBMRU1FTlRPPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT44PC9Db2x1bmE+PEluaWNpbz4yODA8L" +
            "0luaWNpbz48VGFtYW5obz4zMDwvVGFtYW5obz48RGVsaW1pdGFkb3I+PC9EZWxpbWl0YWRvcj48L0Zvc" +
            "m1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+QkFJUlJPPC9Ob" +
            "21lQXRyaWJ1dG8+PENvbHVuYT45PC9Db2x1bmE+PEluaWNpbz4zMTA8L0luaWNpbz48VGFtYW5obz41M" +
            "DwvVGFtYW5obz48RGVsaW1pdGFkb3I+PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjYW9QbGFuaWxoYT48R" +
            "m9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Q0lEQURFPC9Ob21lQXRyaWJ1dG8+PENvbHVuY" +
            "T4xMDwvQ29sdW5hPjxJbmljaW8+MzYwPC9JbmljaW8+PFRhbWFuaG8+NTA8L1RhbWFuaG8+PERlbGlta" +
            "XRhZG9yPjwvRGVsaW1pdGFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoY" +
            "T48Tm9tZUF0cmlidXRvPlRFTEVGT05FPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4xMTwvQ29sdW5hPjxJb" +
            "mljaW8+NDEwPC9JbmljaW8+PFRhbWFuaG8+MTg8L1RhbWFuaG8+PERlbGltaXRhZG9yPjwvRGVsaW1pd" +
            "GFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvP" +
            "lRFTEVGT05FU01TPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4xMjwvQ29sdW5hPjxJbmljaW8+NDI4PC9Jb" +
            "mljaW8+PFRhbWFuaG8+MTI8L1RhbWFuaG8+PERlbGltaXRhZG9yPjwvRGVsaW1pdGFkb3I+PC9Gb3JtY" +
            "XRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPkNPRElHT0JBUlJBV" +
            "k9MVU1FPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4xMzwvQ29sdW5hPjxJbmljaW8+NDUyPC9JbmljaW8+P" +
            "FRhbWFuaG8+MTI8L1RhbWFuaG8+PERlbGltaXRhZG9yPjwvRGVsaW1pdGFkb3I+PC9Gb3JtYXRhY2FvU" +
            "GxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPlNFUlZJQ09FQ1Q8L05vbWVBd" +
            "HJpYnV0bz48Q29sdW5hPjE0PC9Db2x1bmE+PEluaWNpbz40NjQ8L0luaWNpbz48VGFtYW5obz4xMjwvV" +
            "GFtYW5obz48RGVsaW1pdGFkb3I+PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9yb" +
            "WF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+VUY8L05vbWVBdHJpYnV0bz48Q29sdW5hPjE1PC9Db" +
            "2x1bmE+PEluaWNpbz40NzY8L0luaWNpbz48VGFtYW5obz4yPC9UYW1hbmhvPjxEZWxpbWl0YWRvcj48L" +
            "0RlbGltaXRhZG9yPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+PE5vbWVBd" +
            "HJpYnV0bz5EVE5PVEFGSVNDQUw8L05vbWVBdHJpYnV0bz48Q29sdW5hPjE2PC9Db2x1bmE+PEluaWNpb" +
            "z40Nzg8L0luaWNpbz48VGFtYW5obz44PC9UYW1hbmhvPjxEZWxpbWl0YWRvcj48L0RlbGltaXRhZG9yP" +
            "jwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5OUk5PV" +
            "EFGSVNDQUw8L05vbWVBdHJpYnV0bz48Q29sdW5hPjE3PC9Db2x1bmE+PEluaWNpbz40ODY8L0luaWNpb" +
            "z48VGFtYW5obz4xMDwvVGFtYW5obz48RGVsaW1pdGFkb3I+PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjY" +
            "W9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+U0VSSUVOT1RBRklTQ0FMP" +
            "C9Ob21lQXRyaWJ1dG8+PENvbHVuYT4xODwvQ29sdW5hPjxJbmljaW8+NDk2PC9JbmljaW8+PFRhbWFua" +
            "G8+NjwvVGFtYW5obz48RGVsaW1pdGFkb3I+PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjYW9QbGFuaWxoY" +
            "T48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+VkxSTk9UQUZJU0NBTDwvTm9tZUF0cmlid" +
            "XRvPjxDb2x1bmE+MTk8L0NvbHVuYT48SW5pY2lvPjUwMjwvSW5pY2lvPjxUYW1hbmhvPjEwPC9UYW1hb" +
            "mhvPjxEZWxpbWl0YWRvcj48L0RlbGltaXRhZG9yPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY" +
            "2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5QUk9UT0NPTE9OT1RBRklTQ0FMPC9Ob21lQXRyaWJ1dG8+P" +
            "ENvbHVuYT4yMDwvQ29sdW5hPjxJbmljaW8+NTEyPC9JbmljaW8+PFRhbWFuaG8+MjA8L1RhbWFuaG8+P" +
            "ERlbGltaXRhZG9yPjwvRGVsaW1pdGFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9Qb" +
            "GFuaWxoYT48Tm9tZUF0cmlidXRvPkNPRElHT0JBUlJBQ0xJRU5URTwvTm9tZUF0cmlidXRvPjxDb2x1b" +
            "mE+MjE8L0NvbHVuYT48SW5pY2lvPjUzMjwvSW5pY2lvPjxUYW1hbmhvPjUwPC9UYW1hbmhvPjxEZWxpb" +
            "Wl0YWRvcj48L0RlbGltaXRhZG9yPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsa" +
            "GE+PE5vbWVBdHJpYnV0bz5PQlNFUlZBQ0FPTk9UQUZJU0NBTDwvTm9tZUF0cmlidXRvPjxDb2x1bmE+M" +
            "jI8L0NvbHVuYT48SW5pY2lvPjU4MjwvSW5pY2lvPjxUYW1hbmhvPjUwPC9UYW1hbmhvPjxEZWxpbWl0Y" +
            "WRvcj48L0RlbGltaXRhZG9yPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjwvQXJyYXlPZkZvcm1hdGFjYW9Qb" +
            "GFuaWxoYT4=")]
        public string LayoutBifarma {
            get {
                return ((string)(this["LayoutBifarma"]));
            }
            set {
                this["LayoutBifarma"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vpsrv.visualset.com.br/PostagemVipp.asmx")]
        public string WindowsFormsApplication1_WSVIPP_PostagemVipp {
            get {
                return ((string)(this["WindowsFormsApplication1_WSVIPP_PostagemVipp"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsuarioFtp {
            get {
                return ((string)(this["UsuarioFtp"]));
            }
            set {
                this["UsuarioFtp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SenhaFtp {
            get {
                return ((string)(this["SenhaFtp"]));
            }
            set {
                this["SenhaFtp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServidorFtp {
            get {
                return ((string)(this["ServidorFtp"]));
            }
            set {
                this["ServidorFtp"] = value;
            }
        }
    }
}
